name: Python CI with Pre-commit

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest  # or 'macos-latest' or 'windows-latest'

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  # You can adjust this version if needed

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install -r requirements.txt
        pip install black flake8 pytest
    
    # Step 4: Linting (black)
    - name: Check formatting with black
      run: black --check .

    # Step 4: Linting (flake8)
    - name: Lint with flake8
      run: flake8 .

    # Step 5: Run Pytest tests
    - name: Run tests
      run: pytest -v
